stages:
  - test
  - build
  - publish

# Allow to cache files untracked by git, false by default, useful for keeping the build directory,
# between two stages.
cache:
  untracked: true

# Test the project and report the code coverage completion. 
test:
  stage: test
  script:
    - bash gradlew --no-daemon clean test jacocoTestReport
  tags:
    - sapa

# Build the project and create the spring-boot jar.
build:
  stage: build
  script:
    - bash gradlew --no-daemon build
    - docker build . -t depot.domus.usherbrooke.ca:4567/sapa/activity-agent-api:latest
  only:
    - tags
  tags:
    - sapa
  artifacts:
    untracked: true
    paths:
      - ./build/libs/server.jar

publish.docker:
  stage: publish
  only:
    - tags
  script:
    - docker push depot.domus.usherbrooke.ca:4567/sapa/activity-agent-api:latest
  tags:
    - sapa
  dependencies:
    - build
