stages:
  - test
  - build
  - publish

# Allow to cache files untracked by git, false by default, useful for keeping the build directory,
# between two stages.
cache:
  untracked: true

# Test the project and report the code coverage completion. 
test:
  stage: test
  script:
    - bash gradlew --no-daemon clean test jacocoTestReport
  tags:
    - Gradle
    - Java 8.X

# Build the project and create the spring-boot jar.
build:
  stage: build
  script:
    - bash gradlew --no-daemon build
  only:
    - tags
  tags:
    - Gradle
    - Java 8.X
  artifacts:
    untracked: true
    paths:
      - ./build/libs/server.jar

publish.development:
  stage: publish
  only:
    - tags
    - development
  script:
    - rm .git
    - git init
    - git add /build/libs/server.jar
    - git add Dockerfile
    - git remote add dokku dokku@apps.cedric-demongivert.com:domus-api
    - git push master dokku
  tags:
    - NodeJS
    - NPM
  dependencies:
    - build
