stages:
  - test
  - build
  - publish

# Allow to cache files untracked by git, false by default, useful for keeping the build directory,
# between two stages.
cache:
  untracked: true

# Test the project and report the code coverage completion. 
test:
  stage: test
  script:
    - bash gradlew --no-daemon clean test jacocoTestReport
  tags:
    - Gradle
    - Java 8.X

# Build the project and create the spring-boot jar.
build:
  stage: build
  script:
    - bash gradlew --no-daemon build
  only:
    - tags
  tags:
    - Gradle
    - Java 8.X
  artifacts:
    untracked: true
    paths:
      - ./build/libs/server.jar

#publish:
#  stage: publish
#  only:
#    - tags
#  script:
#    - npm publish
#  tags:
#    - NodeJS
#    - NPM
#  dependencies:
#    - build
